language: node_js
node_js:
  - '12'
  - '10'
  - '8'
matrix:
  include:
    - node_js: '12'
      env: INTEGRATION=true LINT=true SKIP_TEST=true
script:
  - if [[ $INTEGRATION == true ]]; then npm run integration; fi
  - if [[ $LINT == true ]]; then npm run lint; fi
  - if [[ $SKIP_TEST != true ]]; then npm test; fi
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
