name: CI

on:
  - push
  - pull_request

jobs:
  test:
    name: Node.js ${{ matrix.node_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node_version:
          - 13
          - 12
          - 10
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - run: npm install
      - run: npm run test
      - uses: codecov/codecov-action@v1
        if: matrix.os == 'ubuntu-latest' && matrix.node_version == 12
        with:
          fail_ci_if_error: true

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm run lint

  integration:
    runs-on: ubuntu-latest
    env:
      CI: 1
      TIMING: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - uses: actions/cache@v1
        # Prevent error on re-run, ref https://github.com/actions/cache/issues/107#issuecomment-556037278
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        with:
          path: test/integration/fixtures
          key: v1-build-cache-${{ github.ref }}-${{ hashFiles('package.json') }}-${{ hashFiles('test/integration/*') }}-
          restore-keys: |
            v1-build-cache-${{ github.ref }}-${{ hashFiles('package.json') }}-${{ hashFiles('test/integration/*') }}-
            v1-build-cache-master-${{ hashFiles('package.json') }}-${{ hashFiles('test/integration/*') }}-
      - run: npm run integration
